services:
  api:
    build: .
    container_name: spreadsheet-broker-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - UVICORN_WORKERS=2
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers ${UVICORN_WORKERS:-2}

